### ISSUE TITLE
502 bad gateway

### ISSUE THREAD

**Issue by FranklinYu** [kaueraal/bugzillatoatom#3]
I filled in following bug:

https://bugzilla.mozilla.org/show_bug.cgi?id=256718

I got “502 Bad Gateway” afterwards.

**Comment by kaueraal** [comment]
What do you mean by "afterwards"?

**Comment by FranklinYu** [comment]
1. Go to https://bugzillatoatom.affine.space/
2. fill in https://bugzilla.mozilla.org/show_bug.cgi?id=256718
3. Hit the RSS icon, or hit enter
4. Expected to see the Atom feed; actually see “502 Bad Gateway”.

**Comment by FranklinYu** [comment]
Cannot reproduce today. I guess it is resolved.
