### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by FranklinYu** [kaueraal/bugzillatoatom#4]
I don’t want to install Golang locally. Would you like to provide a `Dockerfile` so that we can run it in Docker container? Can PR if you like.

**Comment by kaueraal** [comment]
Docker is out of scope of this repository. A Dockerfile fits somewhere else way better.

**Comment by FranklinYu** [comment]
What do you mean by “somewhere else”? `Dockerfile` typically belongs to the corresponding project.
